#########################################################
# !! This code was generated by Gemini AI to create     #
# randomized data sets with x and O's to train with!!   #
#this crets x and os 
#########################################################

import os
import random
from PIL import Image, ImageDraw

def generate_dataset():
    # Define splits and how many images we want per class
    splits = {'train': 800, 'test': 200}
    
    for split, count in splits.items():
        for label in ['X', 'O']:
            folder_path = f"data/{split}/{label}"
            os.makedirs(folder_path, exist_ok=True)
            
            for i in range(count):
                # Start with a black 28x28 canvas
                img = Image.new('L', (28, 28), color=0)
                draw = ImageDraw.Draw(img)
                
                # Introduce slight random shifts in positioning
                dx = random.randint(-2, 2)
                dy = random.randint(-2, 2)
                cx, cy = 14 + dx, 14 + dy
                
                # Randomize line thickness
                thickness = random.randint(1, 2)
                
                if label == 'O':
                    # Draw a circle with a random radius
                    r = random.randint(7, 10)
                    draw.ellipse([cx-r, cy-r, cx+r, cy+r], outline=255, width=thickness)
                    
                    # 50% chance to add a diagonal slash through the zero
                    if random.random() < 0.5:
                        draw.line([cx - r, cy - r, cx + r, cy + r], fill=255, width=thickness)
                        
                else:
                    # Draw an X with a random size
                    size = random.randint(6, 9)
                    draw.line([cx-size, cy-size, cx+size, cy+size], fill=255, width=thickness)
                    draw.line([cx-size, cy+size, cx+size, cy-size], fill=255, width=thickness)
                
                # Save the image into the corresponding folder
                img.save(f"{folder_path}/{label}_{i}.png")

if __name__ == "__main__":
    generate_dataset()
    print("Dataset generation complete! Check your data/ folder.")